sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Z9LUGcrjYkO5v0TMRymrDmH0P3KCYpLTs1Wr/bAgr2PZ09cpGrxs8x59zjqS87IS9HZDf3i8DO6P1gIBLwcpKipqJNdZVvDI3Sa3FtpMV6UkggSQ6WyidRKfAdhYn5dmVY7LGCPgO8KLRPjxfObO1NNE0tkcEOHlTBc1btvlKsJH9EyzcATvQsecl2zPCZgibQG78KizcG7w8RJIrbDCxr7zXnw3yucByhZOku1pwJQNGfhoAPSG65ujf5HBJtJrgne61V46DM4bKh887FX5bMX2a1Z3IdtcGPtXrmLCFRC7/KkMmdVpkra6IUpAZuEB8IFlscCUr4V2DUPqTy21N629xnVXvJyB4jyI9NB2udwgRI2r7x0qfUOcrKxixggrtcTp4rArAXik4EogTX2PblBtZXX7oskJEagMq4PXgZEs4jVgaeIpPt6isZ3MgumC0myrvN//jJw4lKPq5awgH2NJdp8X14+xG1UJ9W7IV4Z9SaPA87WqmSkmo/kTgIyxxumzdsn4zP84MnLAKbf3/6aI4HU069GMwEgmtfoxIXQwzEU2iG+fxBVDx0MPIm4j92XqJYL2pkJNbNyp5wL/l5/jH738iXgRIdU2bwA6ZK+fQWBl813MbQGAPLjpA2eXMGiQOU+YErOqC/+1gtMwM9HXpmmy6HQbWMARTYH4AR8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Love-s-Pilgrimage--A-Novel_5964
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy